"""
Load the raw binary generated by 'genzignor.c'

This is a quick-and-dirty approach, which works on x86-64 gcc system and
may work on other systems, if all elements (zignormw code and Python stack)
have been compiled by similar compilers on one an the same system.

"""
import numpy as np
import matplotlib.pyplot as plt


# This points to a file generated using
#   $ ./genzignor.exe  0 100000000 normalrandoms.bin
fp = "normalrandoms.bin"


with open(fp, "rb") as f:
    norran = np.fromfile(f, dtype=np.float64) 


# Overall histogram
# Close window to continue when running in console

plt.figure(1)
plt.clf()
hcnts, hbins, hobj = plt.hist(norran, bins = 1000, range=(-6.0, 6.0))
plt.show()


# Very rudimentary "scope" mode.
# If you close the scope window, the program will break out of the loop

Ntot = len(norran)
Nsl = 100000
Nbins = 500
ist = 0
FIGNUM = 2
maxscale = 1100
plt.figure(FIGNUM, figsize=(8,3))
while (ist+Nsl <= Ntot) and plt.fignum_exists(FIGNUM):
    plt.clf()
    hcnts, hbins, hobj = plt.hist(norran[ist:ist+Nsl],
                                  bins = Nbins,
                                  range=(-6.0, 6.0))
    plt.ylim(0, maxscale)
    plt.pause(0.2)
    ist+=Nsl

print("Ready")

