"""
Load the binary blob generated by 'test_histogram.c' and plot the histogram

This is a quick-and-dirty approach, which works on x86-64 gcc system and
may work on other systems, if all elements (zignormw code and Python stack)
have been compiled by similar compilers on one an the same system.

To make it more portable, we should be more explicit about the exact integer
sizes and double format. But it's OK for now
"""
import numpy as np
import matplotlib.pyplot as plt


fp = "histogram.bin"
fo = "histogram.png"

with open(fp, "rb") as f:
    Nbins = np.fromfile(f, dtype=np.uint32, count=1)[0]
    HV = np.fromfile(f, dtype=np.float64, count = Nbins) 
    H = np.fromfile(f, dtype=np.uint64, count = Nbins)


plt.figure(1)
plt.clf()
plt.plot(HV, H, '.')
plt.savefig(fo, dpi = 300)

