/*
 Run this C program and compare its output to the output generated by 
 the Python/Numpy script `test_pcg64dxsm_numpy_compare.py`. It will 
 (should) produce exactly the same sequences of random integers, also after 
 "jumping". 
 
 This demonstrates that the PCG64DXSM RNG in `randommw.c` is
 working correctly and in conformity to the PCG64DXSM RNG in Numpy.

 The PCG64DXSM initialization code in randommw.c has been modified
 to reproduce exactly the state of the PCG64DXSM RNG obtained by 
 numpy.random.PGC64DXSM(seed = 0) and PGC64DXSM(seed = 12345).
 This is not automatic, since the initialization of PCG64DXSM is not the 
 same in randommw.c and in Numpy.  It is not feasible to use exactly the 
 same initialization of the PCG64DXSM in `randommw.c` as in Numpy. The 
 latter depends on the specific Numpy infrastructure. In `randommw.c`, 
 SplitMix64 is used for initialization.

*/

#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>

#include "randommw.h"

extern void pcg64dxsm_getstateinc(uint64_t *dataptr);
extern uint64_t pcg64dxsm_next();

static void printstate()
{
	uint64_t stateinc[4]; // to store state/inc of pcg64dxsm rng for diagnostic
	
	pcg64dxsm_getstateinc(stateinc);
	printf("state: 0x%016"PRIx64 "%016" PRIx64 "\n", stateinc[0], stateinc[1]);
	printf("inc:   0x%016"PRIx64 "%016" PRIx64 "\n", stateinc[2], stateinc[3]);
}

static void starline()
{
	printf("************************************************************\n");
}


int main(void)
{


	
	uint64_t sseed[2] = {0, 12345};
	uint64_t Njmp[2]     = {7, 64738};

	uint64_t jj, ii;


	for(jj = 0; jj<2; jj++)
	{
		printf("\n");
		starline();
		printf("*** Seed : %"PRIu64"\n", sseed[jj]);
		RanInit("PCG64DXSM", sseed[jj], 0);
		starline();

		printstate();
		printf("\n");
		for (ii = 0; ii < 10; ii++)
		{
			printf("%"PRIu64"\n", pcg64dxsm_next());
		}
		printf("\n");
		printstate();

			
		printf("\n>>> JUMP! (%"PRIu64" steps)\n\n", Njmp[jj]);
		
		RanJumpRan(Njmp[jj]);

		printstate();
		printf("\n");

		for (ii = 0; ii < 10; ii++)
		{
			printf("%"PRIu64"\n", pcg64dxsm_next());
		}
		starline();
		printf("\n");
	}
}
